### ISSUE TITLE
Gps problem

### ISSUE THREAD

**Issue by dongosiddik** [grfc-ru/flutter_telephony_info#1]
ow come it's mandatory to activate GPS to use this package?? I want to use it without turning on GPS. What should I do?

**Comment by leech001** [comment]
Alas, these are the requirements of the android platform to work with the network module [https://developer.android.com/reference/android/telephony/TelephonyManager](https://developer.android.com/reference/android/telephony/TelephonyManager)
If you do not enable GPS the library cannot access the parameters:
- cell id (cid)
- cell signal strenght.

The other parameters are available without GPS.

**Comment by dongosiddik** [comment]
Hello team I want my application to be able to listen to outgoing calls
from the phone dialer application and not within the same application. My
application should be closed but it listens to the state of phone calls in
the background. How can I achieve this?

Le mer. 3 mai 2023 à 12:41, Bulanov Konstantin ***@***.***> a
écrit :

**Comment by leech001** [comment]
Try exploring this article for the application in the background [Android background service with Flutter](https://plugfox.dev/android-background-service-with-flutter/).
Also note that the "flutter_telephony_info" library is not designed to work with calls.
