### ISSUE TITLE
problem to get cellId value on android 11

### ISSUE THREAD

**Issue by dongosiddik** [grfc-ru/flutter_telephony_info#2]
@leech001 Hello
Help me correct this error. It seems that your plugin is not compatible with all versions of Android. I am able to retrieve the 'cellId' on Android 12 but not on Android 11.

this is my code 

  List<TelephonyInfo?>? telephonyInfo;
          final flutterTelephonyInfoPlugin = TelephonyAPI();
          try {
            telephonyInfo = await flutterTelephonyInfoPlugin.getInfo();
              final gsmInfo = telephonyInfo!.first?.cellId;
                 print("Recuperation des infos de la cellule GSM: $gsmInfo");
            if (telephonyInfo != null && telephonyInfo.length > 0) {

               final mLac = gsmInfo!.split("mLac=")[1].split(" ")[0];
               final mCid = gsmInfo.split("mCid=")[1].split(" ")[0];
               print("mLac: $mLac");
               print("mCid: $mCid");
            } else {
              print("La liste telephonyInfo est vide ou null");
            }
          } catch (e) {
            print("Error GMS: ${e.toString()}");
          }

this result on android 11

I/flutter (26722): Error GMS: PlatformException(java.lang.IndexOutOfBoundsException: Index: 1, Size: 1, IndexOutOfBoundsException, Cause: null, Stacktrace: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
I/flutter (26722):      at java.util.ArrayList.get(ArrayList.java:437)
I/flutter (26722):      at n2.a.b(Unknown Source:136)

this result on android 11

GSM: CellIdentityWcdma:{ mLac=3007 mCid=10168601 mPsc=55 mUarfcn=10663 mMcc=613 mMnc=02 mAlphaLong=Orange BF mAlphaShort=Orange mAdditionalPlmns={} mCsgInfo=null}

**Comment by leech001** [comment]
Hi. That's right. I specifically wrote this plugin only for newer versions of Android (>=12), as other plugins did not work well with newer versions. As an example I used this one[ https://pub.dev/packages/carrier_info]( https://pub.dev/packages/carrier_info)

**Comment by dongosiddik** [comment]
@leech001 hello 
I often get this exception. How can i fix this problem

I/flutter ( 8862): Error GSM: PlatformException(java.lang.IndexOutOfBoundsException: Index: 2, Size: 2, IndexOutOfBoundsException, Cause: null, Stacktrace: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
I/flutter ( 8862):      at java.util.ArrayList.get(ArrayList.java:437)
I/flutter ( 8862):      at n2.a.b(Unknown Source:136)

this is my code 

          List<TelephonyInfo?>? telephonyInfo;
          final flutterTelephonyInfoPlugin = TelephonyAPI();
          try {
          telephonyInfo = await flutterTelephonyInfoPlugin.getInfo();

          } on PlatformException catch(e) {
            telephonyInfo = null;
            
            print("Error GSM: ${e.toString()}");
          }

**Comment by leech001** [comment]
Under which version of android do you run this code?

**Comment by dongosiddik** [comment]
on android 12

**Comment by leech001** [comment]
Tested the library on an example on the Android emulator version 11. Everything works correctly.

![image](https://github.com/grfc-ru/flutter_telephony_info/assets/17683444/706fdf1a-35c4-4c87-9331-3ca005076e8b)

Once again, please check if the GPS is enabled in high accuracy mode. If it is not, you will get not an error, but instead of the right value, the message "Error! GPS must be turned on."
